# Generated by Django 3.2.6 on 2021-08-08 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gymnast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('level', models.CharField(choices=[('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')], max_length=3)),
                ('age_group', models.CharField(choices=[('u8', 'Under 8'), ('u10', 'Under 10'), ('u12', 'Under 12'), ('u15', 'Under 15'), ('o15', 'Over 15')], max_length=3)),
                ('club', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredAparatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aparatus_name', models.CharField(max_length=32)),
                ('gymnast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.gymnast')),
            ],
        ),
    ]
